<?php
/*============================================================================
 * Project Name: %project.name%
 * File: CobaDehComponent.php
 *---------------------------------------------------------------------------
 * LICENSE :
 *---------------------------------------------------------------------------
 * Original Author of this file: ____________________
 * Purpose of this file: ____________________
 *---------------------------------------------------------------------------
 * Generated by AksiIDE - KIOSS Project IDE for PHP
 * @url http://www.aksiide.com
 * @Generated date 2014-08-14 14:50:29
 * @package
 * @updateby
 * @updateon
 *
 * @Usage
 *   $this->CobaDeh->example();
 *
 *============================================================================
 */
App::uses('Component', 'Controller');

class CobaDehComponent extends Component
{
    public $name = 'CobaDeh';


    public function example()
    {
        return true;
    }
    /* */
}
