<?php
/**
 * Project Name: %project_name%
 * File: Common.php
 *
 * Generated by AksiIDE - Light IDE for PHP
 * @url http://www.aksiide.com
 *
 * @author     ______________________
 * @copyright
 * @Generated %date%
 * @package    %module_name%
 * @generator  AksiIDE, http://www.aksiide.com
 *
 **/



/**
 * Common helper functions and constants.
 *
 * $liVar = %module_name%_Helper_Common::Your_Constanta;
 */


class %module_name%_Helper_Common extends Zikula_AbstractHelper
{
	const Your_Constanta = 0;

	/**
	 * Constructs an instance of this helper class.
	 */
	public function __construct(){
	}

	public function function_name(){
	}



}

