<?php
/*============================================================================
 * Project Name: %project.name%
 * File: %filename%
 *---------------------------------------------------------------------------
 * LICENSE :
 *---------------------------------------------------------------------------
 * Original Author of this file: ____________________
 * Purpose of this file: ____________________
 *---------------------------------------------------------------------------
 * Generated by AksiIDE - KIOSS Project IDE for PHP
 * @url http://www.aksiide.com
 * @Generated date %date%
 * @package
 * @updateby
 * @updateon
 *
 * @Usage
 *   $this->%component_name%->example();
 *
 *============================================================================
 */
App::uses('Component', 'Controller');

class %component_name%Component extends Component
{

    public function example()
    {
        $YourModel = ClassRegistry::init('ModelName');


        return true;
    }

    /* */
}
