<!DOCTYPE html>
<html>
<head>
	<title><?php echo $sAppName; ?></title>
  <style>
  code {
  	border-top:1px solid #efefef;
  }
  </style>
</head>
<body>
<h3>Welcome <?php echo $sAppName; ?></h3>
This is example app with <a href="http://panadaframework.com/">Panada</a>
<br />Generated by <a href="http://www.aksiide.com">AksiIDE</a>
<p>Try access page <a href="<?php echo $sBaseURL; ?>index.php/dashboard">Dashboard</a></p>

<code>
file: 'views/home.php'
</code>

</body>
</html>
