<?php
/**
 * Project Name: %project_name%
 * File: %model_name%.php
 *
 * Generated by AksiIDE - Light IDE for PHP
 * @url http://www.aksiide.com
 *
 * @author     ______________________
 * @copyright
 * @Generated date %date%
 * @package   %project_name%
 * @subpackage
 * @deprecated
 * @generator  AksiIDE, http://www.aksiide.com
 *
 **/


/**
 * class %module_name%_DBObject_%model_name%
 *
 * @extends DBObjectArray
 * @package
 **/
class %module_name%_DBObject_%model_name% extends DBObjectArray
{

	public function __construct($init = null, $key = 0, $field = null)
    {
		parent::__construct();
		$this->_objType       = '%table_name%';
		$this->_objField      = '%primary_key%'; //-- gagal masuk ke variabel
		$this->_objPath       = '%table_name%';
		$this->_objKey        = '%primary_key%';

		/*
		$this->_objJoin[]     = array (
			'join_table'          =>  'users',
		  'join_field'          =>  'uname',
		  'object_field_name'   =>  'username',
		  'compare_field_table' =>  'update_by',
		  'compare_field_join'  =>  'uid'
		);

		*/


		$this->_init($init, $key, $this->_objField);
	}

}

