<?php
/**
 * Project Name: %project_name%
 * File: controller.php
 *
 * Generated by AksiIDE - Light IDE for PHP
 * @url http://www.aksiide.com
 *
 * @author     ______________________
 * @copyright
 * @Generated date %date%
 * @package
 * @generator  AksiIDE, http://www.aksiide.com
 *
 **/


namespace %module_name%\Controller;

use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;


/**
 * class %controller_name%Controller
 *
 * @extends AbstractActionController
 * @package
 **/
class %controller_name%Controller extends AbstractActionController {


/**
 * function indexAction
 * @return
 **/
public function indexAction() {
	// get request
	// do something
	// return view object
	return array('id' => $id, 'form' => $form);
}

}

