<?php
/*============================================================================
 * Project Name: %project.name%
 * File: %filename%
 *---------------------------------------------------------------------------
 * LICENSE :
 *---------------------------------------------------------------------------
 * Original Author of this file: ____________________
 * Purpose of this file: ____________________
 *---------------------------------------------------------------------------
 * Generated by AksiIDE - KIOSS Project IDE for PHP
 * @url http://www.aksiide.com
 * @Generated date %date%
 * @package
 * @updateby
 * @updateon
 *
 *============================================================================
 */

App::uses( 'AppModel', 'Model' );

class %model_name% extends AppModel
{
	public $name = '%model_name%';  //note: TablenameSetting
	public $useTable = '%table_name%'; //note: table name
	public $primaryKey = '%primary_key%';
	public $useDbConfig = 'default'; //note: db config --> see 'app/Config/database.php'
    public $tablePrefix = '';

    public function __construct( )
    {
        parent::__construct( );
    }

	function beforeSave($options = array())
	{

	}

	function afterSave($options = array())
	{

	}

    /* */
}


